const products = {
  Sugar: [
    {
      quantity: 1,
      id: 1,
      Category: "Sugar",
      Name: "Avanti Sugar Cubes ",
      Weight: 126,
      Unit: "Cubes",
      MRP: 65,
      SP: 57,
    },
    {
      quantity: 1,
      id: 2,
      Category: "Sugar",
      Name: "Madhur Pure &amp; Hygienic Sugar (M) ",
      Weight: 5,
      Unit: "kgs",
      MRP: 295,
      SP: 228,
    },
    {
      quantity: 1,
      id: 3,
      Category: "Sugar",
      Name: "Mawana Brown Sugar Sachet ",
      Weight: 1,
      Unit: "kg",
      MRP: 200,
      SP: 140,
    },
    {
      quantity: 1,
      id: 4,
      Category: "Sugar",
      Name: "Mawana White Sugar Sachet ",
      Weight: 1,
      Unit: "kg",
      MRP: 160,
      SP: 95,
    },
    {
      quantity: 1,
      id: 5,
      Category: "Sugar",
      Name: "Premia Sugar Candy ",
      Weight: 200,
      Unit: "gm",
      MRP: 26,
      SP: 21,
    },
    {
      quantity: 1,
      id: 6,
      Category: "sugar",
      Name: "Mawana Brown Sugar ",
      Weight: 1,
      Unit: "kg",
      MRP: 130,
      SP: 104,
    },
    {
      quantity: 1,
      id: 7,
      Category: "sugar",
      Name: "Mawana Caster Sugar ",
      Weight: 1,
      Unit: "kg",
      MRP: 130,
      SP: 70,
    },
    {
      quantity: 1,
      id: 8,
      Category: "sugar",
      Name: "Mawana Icing Sugar ",
      Weight: 1,
      Unit: "kg",
      MRP: 140,
      SP: 80,
    },
    {
      quantity: 1,
      id: 9,
      Category: "sugar",
      Name: "Organic Tattva Brown Sugar ",
      Weight: 500,
      Unit: "gm",
      MRP: 75,
      SP: 52,
    },
    {
      quantity: 1,
      id: 10,
      Category: "sugar",
      Name: "Organic Tattva Sugar ",
      Weight: 1,
      Unit: "kg",
      MRP: 140,
      SP: 93,
    },
    {
      quantity: 1,
      id: 11,
      Category: "sugar",
      Name: "Organic Tattva Suji ",
      Weight: 500,
      Unit: "gm",
      MRP: 55,
      SP: 36,
    },
    {
      quantity: 1,
      id: 12,
      Category: "sugar",
      Name: "Paawak Jaggery Cubes Jar ",
      Weight: 500,
      Unit: "gm",
      MRP: 100,
      SP: 65,
    },
    {
      quantity: 1,
      id: 13,
      Category: "sugar",
      Name: "Pitambari Ruchiyana Jaggery Powder  Chemical Free ",
      Weight: 500,
      Unit: "gm",
      MRP: 75,
      SP: 37,
    },
    {
      quantity: 1,
      id: 14,
      Category: "sugar",
      Name: "24 Mantra Organic Sonamasuri Brown Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 95,
      SP: 88,
    },
  ],
  Spice: [
    {
      quantity: 1,
      id: 15,
      Category: "Spices",
      Name: "Premia Kashmiri Chilli Powder ",
      Weight: 1,
      Unit: "kg",
      MRP: 459,
      SP: 371,
    },
    {
      quantity: 1,
      id: 16,
      Category: "Spices",
      Name: "Premia Red Chilli Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 44,
      SP: 40,
    },
    {
      quantity: 1,
      id: 17,
      Category: "Spices",
      Name: "Premia Reshampatti Chilli Khandela ",
      Weight: 500,
      Unit: "gm",
      MRP: 150,
      SP: 130,
    },
    {
      quantity: 1,
      id: 18,
      Category: "Spices",
      Name: "Ramdev Chilli Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 110,
      SP: 94,
    },
    {
      quantity: 1,
      id: 19,
      Category: "Spices",
      Name: "Badshah Black Pepper Powder ",
      Weight: 50,
      Unit: "gm",
      MRP: 80,
      SP: 40,
    },
    {
      quantity: 1,
      id: 20,
      Category: "Spices",
      Name: "Badshah Chat Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 67,
      SP: 47,
    },
    {
      quantity: 1,
      id: 21,
      Category: "Spices",
      Name: "Badshah Chicken Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 76,
      SP: 56,
    },
    {
      quantity: 1,
      id: 22,
      Category: "Spices",
      Name: "Badshah Hing Compounded ",
      Weight: 50,
      Unit: "gm",
      MRP: 95,
      SP: 47,
    },
    {
      quantity: 1,
      id: 23,
      Category: "Spices",
      Name: "Badshah Kitchen King Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 70,
      SP: 53,
    },
    {
      quantity: 1,
      id: 24,
      Category: "Spices",
      Name: "Badshah Rajwadi Garam Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 81,
      SP: 60,
    },
    {
      quantity: 1,
      id: 25,
      Category: "Spices",
      Name: "Bedekar Goda Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 60,
      SP: 45,
    },
    {
      quantity: 1,
      id: 26,
      Category: "Spices",
      Name: "Bedekar Ready Mix Pickle Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 70,
      SP: 55,
    },
    {
      quantity: 1,
      id: 27,
      Category: "Spices",
      Name: "Everest Chaat Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 69,
      SP: 58,
    },
    {
      quantity: 1,
      id: 28,
      Category: "Spices",
      Name: "Everest Chhole Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 67,
      SP: 60,
    },
    {
      quantity: 1,
      id: 29,
      Category: "Spices",
      Name: "Everest Chicken Masala ",
      Weight: 50,
      Unit: "gm",
      MRP: 41,
      SP: 36,
    },
    {
      quantity: 1,
      id: 30,
      Category: "Spices",
      Name: "Everest Coriander Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 66,
      SP: 54,
    },
    {
      quantity: 1,
      id: 31,
      Category: "Spices",
      Name: "Everest Garam Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 84,
      SP: 68,
    },
    {
      quantity: 1,
      id: 32,
      Category: "Spices",
      Name: "Everest Kesari Milk Masala ",
      Weight: 50,
      Unit: "gm",
      MRP: 205,
      SP: 184,
    },
    {
      quantity: 1,
      id: 33,
      Category: "Spices",
      Name: "Everest Kitchen King Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 74,
      SP: 63,
    },
    {
      quantity: 1,
      id: 34,
      Category: "Spices",
      Name: "Everest Meat Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 74,
      SP: 62,
    },
    {
      quantity: 1,
      id: 35,
      Category: "Spices",
      Name: "Everest Pani Puri Masala ",
      Weight: 50,
      Unit: "gm",
      MRP: 33,
      SP: 29,
    },
    {
      quantity: 1,
      id: 36,
      Category: "Spices",
      Name: "Everest Pav Bhaji Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 74,
      SP: 62,
    },
    {
      quantity: 1,
      id: 37,
      Category: "Spices",
      Name: "Everest Sabji Masala ",
      Weight: 50,
      Unit: "gm",
      MRP: 32,
      SP: 26,
    },
    {
      quantity: 1,
      id: 38,
      Category: "Spices",
      Name: "Everest Sambhar Masala ",
      Weight: 50,
      Unit: "gm",
      MRP: 36,
      SP: 30,
    },
    {
      quantity: 1,
      id: 39,
      Category: "Spices",
      Name: "Everest Shahi Biryani Masala ",
      Weight: 50,
      Unit: "gm",
      MRP: 70,
      SP: 58,
    },
    {
      quantity: 1,
      id: 40,
      Category: "Spices",
      Name: "Everest Tandoori Chicken Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 78,
      SP: 68,
    },
    {
      quantity: 1,
      id: 41,
      Category: "Spices",
      Name: "Everest Tea Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 102,
      SP: 88,
    },
    {
      quantity: 1,
      id: 42,
      Category: "Spices",
      Name: "Everest Turmeric Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 64,
      SP: 54,
    },
    {
      quantity: 1,
      id: 43,
      Category: "Spices",
      Name: "Everest Yellow Hing Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 170,
      SP: 150,
    },
    {
      quantity: 1,
      id: 44,
      Category: "Spices",
      Name: "Goldiee Chat Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 62,
      SP: 31,
    },
    {
      quantity: 1,
      id: 45,
      Category: "Spices",
      Name: "Goldiee Chhole Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 72,
      SP: 36,
    },
    {
      quantity: 1,
      id: 46,
      Category: "Spices",
      Name: "Goldiee Chicken Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 62,
      SP: 31,
    },
    {
      quantity: 1,
      id: 47,
      Category: "Spices",
      Name: "Goldiee Garam Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 76,
      SP: 38,
    },
    {
      quantity: 1,
      id: 48,
      Category: "Spices",
      Name: "Goldiee Kashmiri Mirch Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 86,
      SP: 43,
    },
    {
      quantity: 1,
      id: 49,
      Category: "Spices",
      Name: "Goldiee Kitchen King Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 70,
      SP: 35,
    },
    {
      quantity: 1,
      id: 50,
      Category: "Spices",
      Name: "Goldiee Meat Masala Special ",
      Weight: 100,
      Unit: "gm",
      MRP: 78,
      SP: 39,
    },
    {
      quantity: 1,
      id: 51,
      Category: "Spices",
      Name: "Goldiee Pavbhaji Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 64,
      SP: 32,
    },
    {
      quantity: 1,
      id: 52,
      Category: "Spices",
      Name: "Goldiee Sabji Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 56,
      SP: 28,
    },
    {
      quantity: 1,
      id: 53,
      Category: "Spices",
      Name: "Hommade Ginger Garlic Paste ",
      Weight: 200,
      Unit: "gm",
      MRP: 50,
      SP: 30,
    },
    {
      quantity: 1,
      id: 54,
      Category: "Spices",
      Name: "Hommade Tomato Puree ",
      Weight: 200,
      Unit: "gm",
      MRP: 25,
      SP: 22,
    },
    {
      quantity: 1,
      id: 55,
      Category: "Spices",
      Name: "Jalaram Brand Black Pepper Powder ",
      Weight: 50,
      Unit: "gm",
      MRP: 85,
      SP: 57,
    },
    {
      quantity: 1,
      id: 56,
      Category: "Spices",
      Name: "Jalaram Brand Cardamom Powder ",
      Weight: 20,
      Unit: "gm",
      MRP: 110,
      SP: 74,
    },
    {
      quantity: 1,
      id: 57,
      Category: "Spices",
      Name: "Jalaram Brand Cinnamon Powder ",
      Weight: 50,
      Unit: "gm",
      MRP: 75,
      SP: 50,
    },
    {
      quantity: 1,
      id: 58,
      Category: "Spices",
      Name: "Jalaram Brand Kashmiri Milk Masala ",
      Weight: 20,
      Unit: "gm",
      MRP: 94,
      SP: 65,
    },
    {
      quantity: 1,
      id: 59,
      Category: "Spices",
      Name: "Jalaram Brand Nutmeg (Jaifal) Powder ",
      Weight: 10,
      Unit: "gm",
      MRP: 35,
      SP: 24,
    },
    {
      quantity: 1,
      id: 60,
      Category: "Spices",
      Name: "Jalaram Brand Tea Masala with Saffron ",
      Weight: 20,
      Unit: "gm",
      MRP: 60,
      SP: 42,
    },
    {
      quantity: 1,
      id: 61,
      Category: "Spices",
      Name: "Jalaram Kesar (Saffron) ",
      Weight: 1,
      Unit: "gm",
      MRP: 280,
      SP: 199,
    },
    {
      quantity: 1,
      id: 62,
      Category: "Spices",
      Name: "Kapol Tea Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 180,
      SP: 155,
    },
    {
      quantity: 1,
      id: 63,
      Category: "Spices",
      Name: "Kapol Usal   Misal Masala ",
      Weight: 500,
      Unit: "gm",
      MRP: 55,
      SP: 45,
    },
    {
      quantity: 1,
      id: 64,
      Category: "Spices",
      Name: "Kubal Coriander Powder ",
      Weight: 500,
      Unit: "gm",
      MRP: 165,
      SP: 82,
    },
    {
      quantity: 1,
      id: 65,
      Category: "Spices",
      Name: "Kubal Ready Mix Pickle Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 60,
      SP: 30,
    },
    {
      quantity: 1,
      id: 66,
      Category: "Spices",
      Name: "Kubal SP Sunday Malvani Masala ",
      Weight: 1,
      Unit: "kg",
      MRP: 740,
      SP: 370,
    },
    {
      quantity: 1,
      id: 67,
      Category: "Spices",
      Name: "Kubal Sunday Malvani Masala ",
      Weight: 200,
      Unit: "gm",
      MRP: 150,
      SP: 75,
    },
    {
      quantity: 1,
      id: 68,
      Category: "Spices",
      Name: "Kubal Turmeric Powder ",
      Weight: 500,
      Unit: "gm",
      MRP: 150,
      SP: 75,
    },
    {
      quantity: 1,
      id: 69,
      Category: "Spices",
      Name: "Kulith (Horse Gram) ",
      Weight: 500,
      Unit: "gm",
      MRP: 52,
      SP: 43,
    },
    {
      quantity: 1,
      id: 70,
      Category: "Spices",
      Name: "Lapsi Rava / Daliya ",
      Weight: 500,
      Unit: "gm",
      MRP: 30,
      SP: 24,
    },
    {
      quantity: 1,
      id: 71,
      Category: "Spices",
      Name: "LG Hing ",
      Weight: 200,
      Unit: "gm",
      MRP: 304,
      SP: 245,
    },
    {
      quantity: 1,
      id: 72,
      Category: "Spices",
      Name: "Maggi Magic Cubes ",
      Weight: 40,
      Unit: "gm",
      MRP: 35,
      SP: 32,
    },
    {
      quantity: 1,
      id: 73,
      Category: "Spices",
      Name: "Maggi Masala A  Magic ",
      Weight: 72,
      Unit: "gm",
      MRP: 60,
      SP: 52,
    },
    {
      quantity: 1,
      id: 74,
      Category: "Spices",
      Name: "Masala Elaichi ",
      Weight: 50,
      Unit: "gm",
      MRP: 102,
      SP: 78,
    },
    {
      quantity: 1,
      id: 75,
      Category: "Spices",
      Name: "Matki ",
      Weight: 500,
      Unit: "gm",
      MRP: 75,
      SP: 60,
    },
    {
      quantity: 1,
      id: 76,
      Category: "Spices",
      Name: "Matki Small ",
      Weight: 500,
      Unit: "gm",
      MRP: 101,
      SP: 84,
    },
    {
      quantity: 1,
      id: 77,
      Category: "Spices",
      Name: "MDH Chana Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 78,
      SP: 58,
    },
    {
      quantity: 1,
      id: 78,
      Category: "Spices",
      Name: "MDH Chicken Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 80,
      SP: 64,
    },
    {
      quantity: 1,
      id: 79,
      Category: "Spices",
      Name: "MDH Chunky Chat Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 78,
      SP: 65,
    },
    {
      quantity: 1,
      id: 80,
      Category: "Spices",
      Name: "MDH Deggi Mirch ",
      Weight: 100,
      Unit: "gm",
      MRP: 89,
      SP: 70,
    },
    {
      quantity: 1,
      id: 81,
      Category: "Spices",
      Name: "MDH Garam Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 92,
      SP: 73,
    },
    {
      quantity: 1,
      id: 82,
      Category: "Spices",
      Name: "MDH Kitchen King Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 79,
      SP: 65,
    },
    {
      quantity: 1,
      id: 83,
      Category: "Spices",
      Name: "MDH Pav Bhaji Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 81,
      SP: 65,
    },
    {
      quantity: 1,
      id: 84,
      Category: "Spices",
      Name: "MDH Peacock Kasoori Methi ",
      Weight: 25,
      Unit: "gm",
      MRP: 25,
      SP: 22,
    },
    {
      quantity: 1,
      id: 85,
      Category: "Spices",
      Name: "Mother’s Recipe Ginger Garlic Paste ",
      Weight: 200,
      Unit: "gm",
      MRP: 50,
      SP: 25,
    },
    {
      quantity: 1,
      id: 86,
      Category: "Spices",
      Name: "Mother’s Recipe Kadhai Paneer Masala Mix ",
      Weight: 75,
      Unit: "gm",
      MRP: 55,
      SP: 27,
    },
    {
      quantity: 1,
      id: 87,
      Category: "Spices",
      Name: "Mother’s Recipe Paneer Butter Masala Mix ",
      Weight: 75,
      Unit: "gm",
      MRP: 55,
      SP: 27,
    },
    {
      quantity: 1,
      id: 88,
      Category: "Spices",
      Name: "Mother’s Recipe Rozaana Ginger &amp; Garlic Paste ",
      Weight: 700,
      Unit: "gm",
      MRP: 219,
      SP: 109,
    },
    {
      quantity: 1,
      id: 89,
      Category: "Spices",
      Name: "MTR Idli/Dosa/Chilly Chutney Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 125,
      SP: 115,
    },
    {
      quantity: 1,
      id: 90,
      Category: "Spices",
      Name: "MTR Sambar Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 125,
      SP: 109,
    },
    {
      quantity: 1,
      id: 91,
      Category: "Spices",
      Name: "Nachni ",
      Weight: 1,
      Unit: "kg",
      MRP: 48,
      SP: 40,
    },
    {
      quantity: 1,
      id: 92,
      Category: "Spices",
      Name: "Nutrivalue Moringa Oleifera Drum Stick Leaves Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 170,
      SP: 123,
    },
    {
      quantity: 1,
      id: 93,
      Category: "Spices",
      Name: "Premia Black Pepper Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 112,
      SP: 85,
    },
    {
      quantity: 1,
      id: 94,
      Category: "Spices",
      Name: "Premia Extra Strong Hing Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 160,
      SP: 89,
    },
    {
      quantity: 1,
      id: 95,
      Category: "Spices",
      Name: "Premia Pickle Masala ",
      Weight: 200,
      Unit: "gm",
      MRP: 122,
      SP: 50,
    },
    {
      quantity: 1,
      id: 96,
      Category: "Spices",
      Name: "Premia Yellow Hing Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 90,
      SP: 49,
    },
    {
      quantity: 1,
      id: 97,
      Category: "Spices",
      Name: "Ramdev Coriander Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 75,
      SP: 61,
    },
    {
      quantity: 1,
      id: 98,
      Category: "Spices",
      Name: "Ramdev Turmeric Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 70,
      SP: 60,
    },
    {
      quantity: 1,
      id: 99,
      Category: "Spices",
      Name: "Rasoi Magic No Onion No Garlic Veg Kolhapuri Spice Mix ",
      Weight: 45,
      Unit: "gm",
      MRP: 53,
      SP: 39,
    },
    {
      quantity: 1,
      id: 100,
      Category: "Spices",
      Name: "Rasoi Magic Paneer Tikka Masala Spice Mix ",
      Weight: 45,
      Unit: "gm",
      MRP: 45,
      SP: 35,
    },
    {
      quantity: 1,
      id: 101,
      Category: "Spices",
      Name: "Suhana Butter Chicken Mix ",
      Weight: 50,
      Unit: "gm",
      MRP: 40,
      SP: 29,
    },
    {
      quantity: 1,
      id: 102,
      Category: "Spices",
      Name: "Tata Sampann Turmeric Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 72,
      SP: 61,
    },
    {
      quantity: 1,
      id: 103,
      Category: "Spices",
      Name: "Vandevi Hing 2001 Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 180,
      SP: 110,
    },
    {
      quantity: 1,
      id: 104,
      Category: "Spices",
      Name: "Vandevi Hing 2001 Powder ",
      Weight: 50,
      Unit: "gm",
      MRP: 90,
      SP: 60,
    },
    {
      quantity: 1,
      id: 105,
      Category: "Spices",
      Name: "Vandevi Hing Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 152,
      SP: 76,
    },
  ],
  "Dry-fruits": [
    {
      quantity: 1,
      id: 106,
      Category: "dry fruit",
      Name: "Kokan Gem Goa Cashew Premium (Kaju) ",
      Weight: 500,
      Unit: "gm",
      MRP: 750,
      SP: 559,
    },
    {
      quantity: 1,
      id: 107,
      Category: "dry fruit",
      Name: "Kokan Gem Goa Cashews Tukda ",
      Weight: 500,
      Unit: "gm",
      MRP: 550,
      SP: 459,
    },
    {
      quantity: 1,
      id: 108,
      Category: "dry fruit",
      Name: "Kokan Gem Kulith Pith ",
      Weight: 200,
      Unit: "gm",
      MRP: 60,
      SP: 40,
    },
    {
      quantity: 1,
      id: 109,
      Category: "dry fruit",
      Name: "Mahafruit Premium Quality Kishmish (Raisins) ",
      Weight: 500,
      Unit: "gm",
      MRP: 215,
      SP: 149,
    },
    {
      quantity: 1,
      id: 110,
      Category: "dry fruit",
      Name: "Makhana ",
      Weight: 200,
      Unit: "gm",
      MRP: 209,
      SP: 182,
    },
    {
      quantity: 1,
      id: 111,
      Category: "dry fruit",
      Name: "Makhana (Foxnuts) ",
      Weight: 100,
      Unit: "gm",
      MRP: 103,
      SP: 86,
    },
    {
      quantity: 1,
      id: 112,
      Category: "dry fruit",
      Name: "Mamra (Puffed Rice) ",
      Weight: 500,
      Unit: "gm",
      MRP: 60,
      SP: 38,
    },
    {
      quantity: 1,
      id: 113,
      Category: "dry fruit",
      Name: "Morya Phool Makhana (Fox Nuts) ",
      Weight: 100,
      Unit: "gm",
      MRP: 130,
      SP: 99,
    },
    {
      quantity: 1,
      id: 114,
      Category: "dry fruit",
      Name: "Nutraj Almond ",
      Weight: 200,
      Unit: "gm",
      MRP: 399,
      SP: 165,
    },
    {
      quantity: 1,
      id: 115,
      Category: "dry fruit",
      Name: "Nutraj Broken Cashew ",
      Weight: 400,
      Unit: "gm",
      MRP: 499,
      SP: 379,
    },
    {
      quantity: 1,
      id: 116,
      Category: "dry fruit",
      Name: "Nutraj California Almonds (Badam) ",
      Weight: 500,
      Unit: "gm",
      MRP: 899,
      SP: 389,
    },
    {
      quantity: 1,
      id: 117,
      Category: "dry fruit",
      Name: "Nutraj California Walnut Kernels (Akrod Magaj) ",
      Weight: 200,
      Unit: "gm",
      MRP: 499,
      SP: 285,
    },
    {
      quantity: 1,
      id: 118,
      Category: "dry fruit",
      Name: "Nutraj California Whole Walnut (Akrod) ",
      Weight: 1,
      Unit: "kg",
      MRP: 999,
      SP: 579,
    },
    {
      quantity: 1,
      id: 119,
      Category: "dry fruit",
      Name: "Nutraj Cashews ",
      Weight: 500,
      Unit: "gm",
      MRP: 699,
      SP: 378,
    },
    {
      quantity: 1,
      id: 120,
      Category: "dry fruit",
      Name: "Nutraj Dry Dates (Chuara  Khareek) ",
      Weight: 500,
      Unit: "gm",
      MRP: 249,
      SP: 149,
    },
    {
      quantity: 1,
      id: 121,
      Category: "dry fruit",
      Name: "Nutraj Iranian Pistachios (Pista) ",
      Weight: 200,
      Unit: "gm",
      MRP: 449,
      SP: 229,
    },
    {
      quantity: 1,
      id: 122,
      Category: "dry fruit",
      Name: "Nutraj Mix Dry Fruits ",
      Weight: 450,
      Unit: "gm",
      MRP: 399,
      SP: 249,
    },
    {
      quantity: 1,
      id: 123,
      Category: "dry fruit",
      Name: "Nutraj Plain Pistachio Kernel ",
      Weight: 100,
      Unit: "gm",
      MRP: 299,
      SP: 199,
    },
    {
      quantity: 1,
      id: 124,
      Category: "dry fruit",
      Name: "Nutraj Premium California Pistachios (Pista) ",
      Weight: 200,
      Unit: "gm",
      MRP: 379,
      SP: 229,
    },
    {
      quantity: 1,
      id: 125,
      Category: "dry fruit",
      Name: "Nutraj Raisins  Kishmish ",
      Weight: 500,
      Unit: "gm",
      MRP: 299,
      SP: 175,
    },
    {
      quantity: 1,
      id: 126,
      Category: "dry fruit",
      Name: "Nutraj Roasted &amp; Salted Pista ",
      Weight: 100,
      Unit: "gm",
      MRP: 199,
      SP: 125,
    },
    {
      quantity: 1,
      id: 127,
      Category: "dry fruit",
      Name: "Organic Tattva Groundnuts (Peanuts) ",
      Weight: 500,
      Unit: "gm",
      MRP: 145,
      SP: 95,
    },
    {
      quantity: 1,
      id: 128,
      Category: "dry fruit",
      Name: "Premia Akrod Magaj (Walnut Kernels) ",
      Weight: 100,
      Unit: "gm",
      MRP: 220,
      SP: 172,
    },
    {
      quantity: 1,
      id: 129,
      Category: "dry fruit",
      Name: "Premia Black Pepper ",
      Weight: 100,
      Unit: "gm",
      MRP: 113,
      SP: 93,
    },
    {
      quantity: 1,
      id: 130,
      Category: "dry fruit",
      Name: "Premia Dry Apricot ",
      Weight: 200,
      Unit: "gm",
      MRP: 310,
      SP: 185,
    },
    {
      quantity: 1,
      id: 131,
      Category: "dry fruit",
      Name: "Premia Dry Coconut ",
      Weight: 500,
      Unit: "gm",
      MRP: 217,
      SP: 178,
    },
    {
      quantity: 1,
      id: 132,
      Category: "dry fruit",
      Name: "Premia Grated Dry Coconut ",
      Weight: 200,
      Unit: "gm",
      MRP: 72,
      SP: 60,
    },
    {
      quantity: 1,
      id: 133,
      Category: "dry fruit",
      Name: "Premia Kismis Black (Raisins) ",
      Weight: 200,
      Unit: "gm",
      MRP: 113,
      SP: 85,
    },
    {
      quantity: 1,
      id: 134,
      Category: "dry fruit",
      Name: "Premia Kismis Black Seedless ",
      Weight: 100,
      Unit: "gm",
      MRP: 47,
      SP: 34,
    },
    {
      quantity: 1,
      id: 135,
      Category: "dry fruit",
      Name: "Premia Mixed Dry Fruits ",
      Weight: 500,
      Unit: "gm",
      MRP: 309,
      SP: 240,
    },
    {
      quantity: 1,
      id: 136,
      Category: "dry fruit",
      Name: "Royal Delight Finest Ajwa Dates ",
      Weight: 250,
      Unit: "gm",
      MRP: 549,
      SP: 390,
    },
    {
      quantity: 1,
      id: 137,
      Category: "dry fruit",
      Name: "Satyam Miri (Black Pepper) ",
      Weight: 100,
      Unit: "gm",
      MRP: 160,
      SP: 114,
    },
    {
      quantity: 1,
      id: 138,
      Category: "dry fruit",
      Name: "Udid (Urad) Black Whole ",
      Weight: 500,
      Unit: "gm",
      MRP: 71,
      SP: 59,
    },
  ],
  Pulses: [
    {
      quantity: 1,
      id: 139,
      Category: "pulses",
      Name: "Badshah Chana Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 66,
      SP: 53,
    },
    {
      quantity: 1,
      id: 140,
      Category: "pulses",
      Name: "Badshah Punjabi Chhole Masala ",
      Weight: 100,
      Unit: "gm",
      MRP: 66,
      SP: 46,
    },
    {
      quantity: 1,
      id: 141,
      Category: "pulses",
      Name: "Chana Big ",
      Weight: 500,
      Unit: "gm",
      MRP: 59,
      SP: 49,
    },
    {
      quantity: 1,
      id: 142,
      Category: "pulses",
      Name: "Chana Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 93,
      SP: 78,
    },
    {
      quantity: 1,
      id: 143,
      Category: "pulses",
      Name: "Chana Green ",
      Weight: 500,
      Unit: "gm",
      MRP: 135,
      SP: 113,
    },
    {
      quantity: 1,
      id: 144,
      Category: "pulses",
      Name: "Chana Small ",
      Weight: 500,
      Unit: "gm",
      MRP: 47,
      SP: 39,
    },
    {
      quantity: 1,
      id: 145,
      Category: "pulses",
      Name: "Dal ",
      Unit: "Mix",
      MRP: " 500gm",
      SP: 47,
    },
    {
      quantity: 1,
      id: 146,
      Category: "pulses",
      Name: "Daliya ",
      Weight: 500,
      Unit: "gm",
      MRP: 68,
      SP: 55,
    },
    {
      quantity: 1,
      id: 147,
      Category: "pulses",
      Name: "Desi Kabuli Chana ",
      Weight: 1,
      Unit: "kg",
      MRP: 184,
      SP: 145,
    },
    {
      quantity: 1,
      id: 148,
      Category: "pulses",
      Name: "DMart Healthy Choice Unpolished Moong Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 167,
      SP: 134,
    },
    {
      quantity: 1,
      id: 149,
      Category: "pulses",
      Name: "DMart Healthy Choice Unpolished Toor Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 172,
      SP: 144,
    },
    {
      quantity: 1,
      id: 150,
      Category: "pulses",
      Name: "Masoor Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 129,
      SP: 106,
    },
    {
      quantity: 1,
      id: 151,
      Category: "pulses",
      Name: "Masoor Whole ",
      Weight: 500,
      Unit: "gm",
      MRP: 65,
      SP: 53,
    },
    {
      quantity: 1,
      id: 152,
      Category: "pulses",
      Name: "Mix Dal ",
      Weight: 500,
      Unit: "gm",
      MRP: 73,
      SP: 60,
    },
    {
      quantity: 1,
      id: 153,
      Category: "pulses",
      Name: "Mixed Pulses For Sprout ",
      Weight: 500,
      Unit: "gm",
      MRP: 64,
      SP: 54,
    },
    {
      quantity: 1,
      id: 154,
      Category: "pulses",
      Name: "Moong Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 149,
      SP: 122,
    },
    {
      quantity: 1,
      id: 155,
      Category: "pulses",
      Name: "Moong Dal Chilti ",
      Weight: 500,
      Unit: "gm",
      MRP: 69,
      SP: 60,
    },
    {
      quantity: 1,
      id: 156,
      Category: "pulses",
      Name: "Moong Whole ",
      Weight: 1,
      Unit: "kg",
      MRP: 142,
      SP: 117,
    },
    {
      quantity: 1,
      id: 157,
      Category: "pulses",
      Name: "Moong Whole Small ",
      Weight: 500,
      Unit: "gm",
      MRP: 68,
      SP: 57,
    },
    {
      quantity: 1,
      id: 158,
      Category: "pulses",
      Name: "Organic Tattva Arhar Tur Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 270,
      SP: 135,
    },
    {
      quantity: 1,
      id: 159,
      Category: "pulses",
      Name: "Organic Tattva Kabuli Chana ",
      Weight: 500,
      Unit: "gm",
      MRP: 145,
      SP: 95,
    },
    {
      quantity: 1,
      id: 160,
      Category: "pulses",
      Name: "Organic Tattva Kala Chana ",
      Weight: 500,
      Unit: "gm",
      MRP: 85,
      SP: 56,
    },
    {
      quantity: 1,
      id: 161,
      Category: "pulses",
      Name: "Organic Tattva Moong Dal Whole ",
      Weight: 500,
      Unit: "gm",
      MRP: 125,
      SP: 82,
    },
    {
      quantity: 1,
      id: 162,
      Category: "pulses",
      Name: "Organic Tattva Moong Dal Yellow Split ",
      Weight: 1,
      Unit: "kg",
      MRP: 270,
      SP: 178,
    },
    {
      quantity: 1,
      id: 163,
      Category: "pulses",
      Name: "Premia Chana Small ",
      Weight: 1,
      Unit: "kg",
      MRP: 92,
      SP: 79,
    },
    {
      quantity: 1,
      id: 164,
      Category: "pulses",
      Name: "Satyam Chana Dal ",
      Weight: 500,
      Unit: "gm",
      MRP: 77,
      SP: 70,
    },
    {
      quantity: 1,
      id: 165,
      Category: "pulses",
      Name: "Satyam Chana Green ",
      Weight: 500,
      Unit: "gm",
      MRP: 159,
      SP: 135,
    },
    {
      quantity: 1,
      id: 166,
      Category: "pulses",
      Name: "Satyam Chana Mosambi ",
      Weight: 500,
      Unit: "gm",
      MRP: 90,
      SP: 78,
    },
    {
      quantity: 1,
      id: 167,
      Category: "pulses",
      Name: "Satyam Chana Small ",
      Weight: 500,
      Unit: "gm",
      MRP: 70,
      SP: 65,
    },
    {
      quantity: 1,
      id: 168,
      Category: "pulses",
      Name: "Satyam Toor Dal Oily ",
      Weight: 500,
      Unit: "gm",
      MRP: 109,
      SP: 100,
    },
    {
      quantity: 1,
      id: 169,
      Category: "pulses",
      Name: "Tata Sampann 100% Organic Unpolished Chana Dal ",
      Weight: 1,
      Unit: "kg",
      MRP: 190,
      SP: 171,
    },
    {
      quantity: 1,
      id: 170,
      Category: "pulses",
      Name: "Tata Sampann Chana Dal ",
      Weight: 500,
      Unit: "gm",
      MRP: 64,
      SP: 48,
    },
    {
      quantity: 1,
      id: 171,
      Category: "pulses",
      Name: "Toor Dal Oily ",
      Weight: 5,
      Unit: "kgs",
      MRP: 750,
      SP: 560,
    },
    {
      quantity: 1,
      id: 172,
      Category: "pulses",
      Name: "Toor Dal Plain ",
      Weight: 5,
      Unit: "kgs",
      MRP: 750,
      SP: 525,
    },
    {
      quantity: 1,
      id: 173,
      Category: "pulses",
      Name: "Tur Dal Latur ",
      Weight: 1,
      Unit: "kg",
      MRP: 141,
      SP: 119,
    },
    {
      quantity: 1,
      id: 174,
      Category: "pulses",
      Name: "Udid (Urad) Dal Chilti ",
      Weight: 500,
      Unit: "gm",
      MRP: 76,
      SP: 62,
    },
  ],
  Flour: [
    {
      quantity: 1,
      id: 175,
      Category: "Flour",
      Name: "Bajari ",
      Weight: 1,
      Unit: "kg",
      MRP: 47,
      SP: 39,
    },
    {
      quantity: 1,
      id: 176,
      Category: "Flour",
      Name: "Bajari Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 35,
      SP: 30,
    },
    {
      quantity: 1,
      id: 177,
      Category: "Flour",
      Name: "Besan ",
      Weight: 1,
      Unit: "kg",
      MRP: 91,
      SP: 79,
    },
    {
      quantity: 1,
      id: 178,
      Category: "Flour",
      Name: "Bhagirathi Bajra Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 35,
      SP: 28,
    },
    {
      quantity: 1,
      id: 179,
      Category: "Flour",
      Name: "Bhagirathi Jowar Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 44,
      SP: 34,
    },
    {
      quantity: 1,
      id: 180,
      Category: "Flour",
      Name: "Bhagirathi Makai (Corn) Flour ",
      Weight: 500,
      Unit: "gm",
      MRP: 36,
      SP: 28,
    },
    {
      quantity: 1,
      id: 181,
      Category: "Flour",
      Name: "Bhagirathi Multigrain Bhakari Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 48,
      SP: 33,
    },
    {
      quantity: 1,
      id: 182,
      Category: "Flour",
      Name: "Bhagirathi Nachani (Ragi) Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 44,
      SP: 37,
    },
    {
      quantity: 1,
      id: 183,
      Category: "Flour",
      Name: "Bhagirathi Rajgira Atta ",
      Weight: 200,
      Unit: "gm",
      MRP: 55,
      SP: 39,
    },
    {
      quantity: 1,
      id: 184,
      Category: "Flour",
      Name: "Bhagirathi Sattu Atta ",
      Weight: 200,
      Unit: "gm",
      MRP: 40,
      SP: 34,
    },
    {
      quantity: 1,
      id: 185,
      Category: "Flour",
      Name: "Bhagirathi Shingada Atta ",
      Weight: 200,
      Unit: "gm",
      MRP: 120,
      SP: 85,
    },
    {
      quantity: 1,
      id: 186,
      Category: "Flour",
      Name: "Blue Bird Corn Flour ",
      Weight: 500,
      Unit: "gm",
      MRP: 80,
      SP: 74,
    },
    {
      quantity: 1,
      id: 187,
      Category: "Flour",
      Name: "Fortune Chana Dal Besan ",
      Weight: 1,
      Unit: "kg",
      MRP: 140,
      SP: 89,
    },
    {
      quantity: 1,
      id: 188,
      Category: "Flour",
      Name: "Makai Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 29,
      SP: 24,
    },
    {
      quantity: 1,
      id: 189,
      Category: "Flour",
      Name: "Nachni Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 31,
      SP: 26,
    },
    {
      quantity: 1,
      id: 190,
      Category: "Flour",
      Name: "Pillsbury Multi Grain Atta ",
      Weight: 5,
      Unit: "kgs",
      MRP: 315,
      SP: 230,
    },
    {
      quantity: 1,
      id: 191,
      Category: "Flour",
      Name: "Weikfield Corn Flour ",
      Weight: 100,
      Unit: "gm",
      MRP: 29,
      SP: 25,
    },
  ],
  Rice: [
    {
      quantity: 1,
      id: 192,
      Category: "rice",
      Name: "Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 113,
      SP: 97,
    },
    {
      quantity: 1,
      id: 193,
      Category: "rice",
      Name: "Basmati Rice Broken (Kani) ",
      Weight: 10,
      Unit: "kgs",
      MRP: 375,
      SP: 345,
    },
    {
      quantity: 1,
      id: 194,
      Category: "rice",
      Name: "Basmati Rice Mini Mogra (Broken) ",
      Weight: 10,
      Unit: "kgs",
      MRP: 650,
      SP: 395,
    },
    {
      quantity: 1,
      id: 195,
      Category: "rice",
      Name: "Biryani Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 700,
      SP: 425,
    },
    {
      quantity: 1,
      id: 196,
      Category: "rice",
      Name: "Daawat Biryani Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 220,
      SP: 172,
    },
    {
      quantity: 1,
      id: 197,
      Category: "rice",
      Name: "Daawat Brown Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 175,
      SP: 139,
    },
    {
      quantity: 1,
      id: 198,
      Category: "rice",
      Name: "Daawat Devaaya Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 572,
      SP: 395,
    },
    {
      quantity: 1,
      id: 199,
      Category: "rice",
      Name: "Daawat Heritage Daily Feast Tukda Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 500,
      SP: 250,
    },
    {
      quantity: 1,
      id: 200,
      Category: "rice",
      Name: "Daawat Pulav Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 135,
      SP: 108,
    },
    {
      quantity: 1,
      id: 201,
      Category: "rice",
      Name: "Daawat Pulav Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 675,
      SP: 559,
    },
    {
      quantity: 1,
      id: 202,
      Category: "rice",
      Name: "Daawat Pulav Basmati Rice ",
      Weight: 500,
      Unit: "gm",
      MRP: 75,
      SP: 49,
    },
    {
      quantity: 1,
      id: 203,
      Category: "rice",
      Name: "Daawat Rozana Basmati Rice ",
      Unit: "Gol",
      MRP: " 5 kgs",
      SP: 560,
    },
    {
      quantity: 1,
      id: 204,
      Category: "rice",
      Name: "Daawat Rozana Mini Mogra 2 (Broken) Rice ",
      Weight: 10,
      Unit: "kgs",
      MRP: 395,
      SP: 309,
    },
    {
      quantity: 1,
      id: 205,
      Category: "rice",
      Name: "Daawat Rozana Super Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 425,
      SP: 339,
    },
    {
      quantity: 1,
      id: 206,
      Category: "rice",
      Name: "Daawat Sehat Mini Mogra (Broken) Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 305,
      SP: 229,
    },
    {
      quantity: 1,
      id: 207,
      Category: "rice",
      Name: "Daawat Sehat Mogra Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 360,
      SP: 309,
    },
    {
      quantity: 1,
      id: 208,
      Category: "rice",
      Name: "Daawat Super Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 920,
      SP: 575,
    },
    {
      quantity: 1,
      id: 209,
      Category: "rice",
      Name: "Daawat Traditional Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 210,
      SP: 186,
    },
    {
      quantity: 1,
      id: 210,
      Category: "rice",
      Name: "Devaaya Biryani Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 200,
      SP: 98,
    },
    {
      quantity: 1,
      id: 211,
      Category: "rice",
      Name: "Devaaya Biryani Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 1000,
      SP: 499,
    },
    {
      quantity: 1,
      id: 212,
      Category: "rice",
      Name: "Eco Kolam Jirasar Sorted Rice ",
      Weight: 10,
      Unit: "kgs",
      MRP: 550,
      SP: 411,
    },
    {
      quantity: 1,
      id: 213,
      Category: "rice",
      Name: "Fortune Biryani Special Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 875,
      SP: 585,
    },
    {
      quantity: 1,
      id: 214,
      Category: "rice",
      Name: "Fortune Everyday Hamesha Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 425,
      SP: 299,
    },
    {
      quantity: 1,
      id: 215,
      Category: "rice",
      Name: "Fortune Mogra Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 375,
      SP: 279,
    },
    {
      quantity: 1,
      id: 216,
      Category: "rice",
      Name: "HMT Kolam Sorted Rice ",
      Weight: 10,
      Unit: "kgs",
      MRP: 850,
      SP: 525,
    },
    {
      quantity: 1,
      id: 217,
      Category: "rice",
      Name: "Idli Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 60,
      SP: 51,
    },
    {
      quantity: 1,
      id: 218,
      Category: "rice",
      Name: "India Gate Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 1085,
      SP: 860,
    },
    {
      quantity: 1,
      id: 219,
      Category: "rice",
      Name: "India Gate Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 645,
      SP: 559,
    },
    {
      quantity: 1,
      id: 220,
      Category: "rice",
      Name: "India Gate Basmati Rice ",
      Weight: 10,
      Unit: "kgs",
      MRP: 390,
      SP: 335,
    },
    {
      quantity: 1,
      id: 221,
      Category: "rice",
      Name: "India Gate Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 425,
      SP: 329,
    },
    {
      quantity: 1,
      id: 222,
      Category: "rice",
      Name: "India Gate Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 725,
      SP: 545,
    },
    {
      quantity: 1,
      id: 223,
      Category: "rice",
      Name: "India Gate Brown Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 152,
      SP: 120,
    },
    {
      quantity: 1,
      id: 224,
      Category: "rice",
      Name: "India Gate Mini Mogra (Broken) Basmati Rice ",
      Weight: 10,
      Unit: "kgs",
      MRP: 660,
      SP: 515,
    },
    {
      quantity: 1,
      id: 225,
      Category: "rice",
      Name: "India Gate Super Basmati Rice ",
      Weight: 5,
      Unit: "kgs",
      MRP: 935,
      SP: 599,
    },
    {
      quantity: 1,
      id: 226,
      Category: "rice",
      Name: "IR Boiled Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 46,
      SP: 38,
    },
    {
      quantity: 1,
      id: 227,
      Category: "rice",
      Name: "Jawari Atta ",
      Weight: 500,
      Unit: "gm",
      MRP: 31,
      SP: 25,
    },
    {
      quantity: 1,
      id: 228,
      Category: "rice",
      Name: "Long Grain Rice ",
      Weight: 10,
      Unit: "kgs",
      MRP: 650,
      SP: 435,
    },
    {
      quantity: 1,
      id: 229,
      Category: "rice",
      Name: "Masoori Boiled Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 49,
      SP: 41,
    },
    {
      quantity: 1,
      id: 230,
      Category: "rice",
      Name: "Mogra Basmati Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 69,
      SP: 55,
    },
    {
      quantity: 1,
      id: 231,
      Category: "rice",
      Name: "Mother’s Recipe Chicken Biryani Mix ",
      Weight: 100,
      Unit: "gm",
      MRP: 55,
      SP: 27,
    },
    {
      quantity: 1,
      id: 232,
      Category: "rice",
      Name: "Rice Basmati Tukda ",
      Weight: 5,
      Unit: "kgs",
      MRP: 490,
      SP: 290,
    },
    {
      quantity: 1,
      id: 233,
      Category: "rice",
      Name: "Rice Basmati Wand ",
      Weight: 5,
      Unit: "kgs",
      MRP: 840,
      SP: 447,
    },
    {
      quantity: 1,
      id: 234,
      Category: "Ricebran",
      Name: "Riso Ricebran Oil ",
      Weight: 1,
      Unit: "Liticr",
      MRP: 225,
      SP: 179,
    },
    {
      quantity: 1,
      id: 235,
      Category: "rice",
      Name: "Suhana Chicken Biryani Mix ",
      Weight: 50,
      Unit: "gm",
      MRP: 40,
      SP: 29,
    },
  ],
  Others: [
    {
      quantity: 1,
      id: 236,
      Category: "others",
      Name: "Bedekar Thalipith Bhajni ",
      Weight: 200,
      Unit: "gm",
      MRP: 45,
      SP: 40,
    },
    {
      quantity: 1,
      id: 237,
      Category: "others",
      Name: "Bhagirathi Thalipeeth Bhajni ",
      Weight: 200,
      Unit: "gm",
      MRP: 45,
      SP: 35,
    },
    {
      quantity: 1,
      id: 238,
      Category: "others",
      Name: "Bhagirathi Upwas Bhajani ",
      Weight: 200,
      Unit: "gm",
      MRP: 55,
      SP: 39,
    },
    {
      quantity: 1,
      id: 239,
      Category: "others",
      Name: "Blue Bird Baking Powder ",
      Weight: 50,
      Unit: "gm",
      MRP: 27,
      SP: 22,
    },
    {
      quantity: 1,
      id: 240,
      Category: "others",
      Name: "Blue Bird Test  Nov Monosodium Glutamate ",
      Weight: 25,
      Unit: "gm",
      MRP: 30,
      SP: 22,
    },
    {
      quantity: 1,
      id: 241,
      Category: "others",
      Name: "Chowli Big ",
      Weight: 500,
      Unit: "gm",
      MRP: 63,
      SP: 53,
    },
    {
      quantity: 1,
      id: 242,
      Category: "others",
      Name: "Chowli Premium ",
      Weight: 500,
      Unit: "gm",
      MRP: 83,
      SP: 68,
    },
    {
      quantity: 1,
      id: 243,
      Category: "others",
      Name: "Chowli Red ",
      Weight: 500,
      Unit: "gm",
      MRP: 73,
      SP: 59,
    },
    {
      quantity: 1,
      id: 244,
      Category: "others",
      Name: "Chowli Small ",
      Weight: 500,
      Unit: "gm",
      MRP: 68,
      SP: 57,
    },
    {
      quantity: 1,
      id: 245,
      Category: "others",
      Name: "Christopher Cocoa Baking Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 199,
      SP: 99,
    },
    {
      quantity: 1,
      id: 246,
      Category: "others",
      Name: "Christopher Cocoa Baking Soda All Purpose ",
      Weight: 250,
      Unit: "gm",
      MRP: 199,
      SP: 99,
    },
    {
      quantity: 1,
      id: 247,
      Category: "others",
      Name: "Et   Mi Baking Powder ",
      Weight: 500,
      Unit: "gm",
      MRP: 25,
      SP: 22,
    },
    {
      quantity: 1,
      id: 248,
      Category: "others",
      Name: "Flying Bird Artificial Food Essence Shahi Biryani ",
      Weight: 20,
      Unit: "ml",
      MRP: 90,
      SP: 70,
    },
    {
      quantity: 1,
      id: 249,
      Category: "others",
      Name: "Jaggery ",
      Weight: 900,
      Unit: "gm",
      MRP: 80,
      SP: 60,
    },
    {
      quantity: 1,
      id: 250,
      Category: "others",
      Name: "Keshar Premium Natural Jaggery Jar ",
      Weight: 900,
      Unit: "gm",
      MRP: 100,
      SP: 90,
    },
    {
      quantity: 1,
      id: 251,
      Category: "others",
      Name: "Kokan Gem Thalipeeth Bhajani ",
      Weight: 200,
      Unit: "gm",
      MRP: 50,
      SP: 35,
    },
    {
      quantity: 1,
      id: 252,
      Category: "others",
      Name: "Kolhapuri Surati Kurmura ",
      Weight: 500,
      Unit: "gm",
      MRP: 80,
      SP: 44,
    },
    {
      quantity: 1,
      id: 253,
      Category: "others",
      Name: "Kubal SP Mix Usal Masala ",
      Weight: 200,
      Unit: "gm",
      MRP: 130,
      SP: 65,
    },
    {
      quantity: 1,
      id: 254,
      Category: "others",
      Name: "Laxmi Jaya Kurmura ",
      Weight: 500,
      Unit: "gm",
      MRP: 60,
      SP: 40,
    },
    {
      quantity: 1,
      id: 255,
      Category: "others",
      Name: "Makai For Popcorn ",
      Weight: 200,
      Unit: "gm",
      MRP: 36,
      SP: 28,
    },
    {
      quantity: 1,
      id: 256,
      Category: "others",
      Name: "Nisarga Desiccated Coconut Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 85,
      SP: 65,
    },
    {
      quantity: 1,
      id: 257,
      Category: "others",
      Name: "Nutrela Soya Chunks ",
      Weight: 200,
      Unit: "gm",
      MRP: 60,
      SP: 52,
    },
    {
      quantity: 1,
      id: 258,
      Category: "others",
      Name: "Nutrela Soya Granules ",
      Weight: 200,
      Unit: "gm",
      MRP: 60,
      SP: 50,
    },
    {
      quantity: 1,
      id: 259,
      Category: "others",
      Name: "Nutrela Soya Mini Chunks ",
      Weight: 200,
      Unit: "gm",
      MRP: 60,
      SP: 52,
    },
    {
      quantity: 1,
      id: 260,
      Category: "others",
      Name: "Organic India Quinoa ",
      Weight: 500,
      Unit: "gm",
      MRP: 295,
      SP: 265,
    },
    {
      quantity: 1,
      id: 261,
      Category: "others",
      Name: "Premia Alsi ",
      Weight: 100,
      Unit: "gm",
      MRP: 24,
      SP: 18,
    },
    {
      quantity: 1,
      id: 262,
      Category: "others",
      Name: "Premia Badishep ",
      Weight: 200,
      Unit: "gm",
      MRP: 86,
      SP: 67,
    },
    {
      quantity: 1,
      id: 263,
      Category: "others",
      Name: "Premia Coconut Powder ",
      Weight: 200,
      Unit: "gm",
      MRP: 73,
      SP: 57,
    },
    {
      quantity: 1,
      id: 264,
      Category: "others",
      Name: "Premia Dhaniya ",
      Weight: 400,
      Unit: "gm",
      MRP: 152,
      SP: 108,
    },
    {
      quantity: 1,
      id: 265,
      Category: "others",
      Name: "Premia Emli ",
      Weight: 500,
      Unit: "gm",
      MRP: 118,
      SP: 94,
    },
    {
      quantity: 1,
      id: 266,
      Category: "others",
      Name: "Premia Groundnut ",
      Weight: 500,
      Unit: "gm",
      MRP: 98,
      SP: 84,
    },
    {
      quantity: 1,
      id: 267,
      Category: "others",
      Name: "Premia Halim ",
      Weight: 100,
      Unit: "gm",
      MRP: 20,
      SP: 16,
    },
    {
      quantity: 1,
      id: 268,
      Category: "others",
      Name: "Premia Jaifal ",
      Weight: 4,
      Unit: "Piec",
      MRP: 65,
      SP: 50,
    },
    {
      quantity: 1,
      id: 269,
      Category: "others",
      Name: "Premia Jardalu ",
      Weight: 100,
      Unit: "gm",
      MRP: 78,
      SP: 61,
    },
    {
      quantity: 1,
      id: 270,
      Category: "others",
      Name: "Premia Jeera ",
      Weight: 200,
      Unit: "gm",
      MRP: 94,
      SP: 72,
    },
    {
      quantity: 1,
      id: 271,
      Category: "others",
      Name: "Premia Kaju ",
      Weight: 500,
      Unit: "gm",
      MRP: 560,
      SP: 437,
    },
    {
      quantity: 1,
      id: 272,
      Category: "others",
      Name: "Premia Kalvanji ",
      Weight: 100,
      Unit: "gm",
      MRP: 34,
      SP: 26,
    },
    {
      quantity: 1,
      id: 273,
      Category: "others",
      Name: "Premia Lawang ",
      Weight: 20,
      Unit: "gm",
      MRP: 38,
      SP: 31,
    },
    {
      quantity: 1,
      id: 274,
      Category: "others",
      Name: "Premia Methi ",
      Weight: 100,
      Unit: "gm",
      MRP: 17,
      SP: 15,
    },
    {
      quantity: 1,
      id: 275,
      Category: "others",
      Name: "Premia Rai ",
      Weight: 200,
      Unit: "gm",
      MRP: 42,
      SP: 31,
    },
    {
      quantity: 1,
      id: 276,
      Category: "others",
      Name: "Premia Sabja ",
      Weight: 100,
      Unit: "gm",
      MRP: 56,
      SP: 39,
    },
    {
      quantity: 1,
      id: 277,
      Category: "others",
      Name: "Premia Sabudana ",
      Weight: 1,
      Unit: "kg",
      MRP: 75,
      SP: 62,
    },
    {
      quantity: 1,
      id: 278,
      Category: "others",
      Name: "Premia Sakariya ",
      Weight: 200,
      Unit: "gm",
      MRP: 20,
      SP: 16,
    },
    {
      quantity: 1,
      id: 279,
      Category: "others",
      Name: "Premia Soyawadi ",
      Weight: 200,
      Unit: "gm",
      MRP: 48,
      SP: 29,
    },
    {
      quantity: 1,
      id: 280,
      Category: "others",
      Name: "Premia Sugar ",
      Weight: 5,
      Unit: "kgs",
      MRP: 267,
      SP: 215,
    },
    {
      quantity: 1,
      id: 281,
      Category: "others",
      Name: "Weikfield Baking Powder ",
      Weight: 50,
      Unit: "gm",
      MRP: 25,
      SP: 20,
    },
  ],
  Oil: [
    {
      quantity: 1,
      id: 282,
      Category: "Oil",
      Name: "Bertolli Extra Light Tasting Olive Oil ",
      Weight: 2,
      Unit: "Liter",
      MRP: 2999,
      SP: 1049,
    },
    {
      quantity: 1,
      id: 283,
      Category: "Oil",
      Name: "Borges Extra Light Olive Oil ",
      Weight: 2,
      Unit: "liter",
      MRP: 2600,
      SP: 1155,
    },
    {
      quantity: 1,
      id: 284,
      Category: "Oil",
      Name: "Borges Extra Virgin Olive Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 1400,
      SP: 775,
    },
    {
      quantity: 1,
      id: 285,
      Category: "Oil",
      Name: "Borges Pure Olive Oil  Classic ",
      Weight: 1,
      Unit: "liter",
      MRP: 1350,
      SP: 639,
    },
    {
      quantity: 1,
      id: 286,
      Category: "oil",
      Name: "Coco Soul Virgin Coconut Oil ",
      Weight: 500,
      Unit: "ml",
      MRP: 449,
      SP: 345,
    },
    {
      quantity: 1,
      id: 287,
      Category: "Oil",
      Name: "Dalda Refined Sunflower Oil Pouch ",
      Weight: 1,
      Unit: "Liter",
      MRP: 225,
      SP: 185,
    },
    {
      quantity: 1,
      id: 288,
      Category: "oil",
      Name: "Dalda Vanaspati ",
      Weight: 1,
      Unit: "Litar",
      MRP: 235,
      SP: 172,
    },
    {
      quantity: 1,
      id: 289,
      Category: "Oil",
      Name: "Del Monte Extra Light Olive Oil ",
      Weight: 2,
      Unit: "liter",
      MRP: 2400,
      SP: 943,
    },
    {
      quantity: 1,
      id: 290,
      Category: "Oil",
      Name: "Dhara Filtered Groundnut Oil Pouch ",
      Weight: 1,
      Unit: "liter",
      MRP: 235,
      SP: 196,
    },
    {
      quantity: 1,
      id: 291,
      Category: "Oil",
      Name: "Dhara Kachighani (Mustard) Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 210,
      SP: 190,
    },
    {
      quantity: 1,
      id: 292,
      Category: "Oil",
      Name: "Dhara Life Refined Rice Bran Oil Jar ",
      Weight: 15,
      Unit: "liter",
      MRP: 3030,
      SP: 2799,
    },
    {
      quantity: 1,
      id: 293,
      Category: "oil",
      Name: "Dhara Refined Rice Bran Oil ",
      Weight: 5,
      Unit: "liter",
      MRP: 1020,
      SP: 925,
    },
    {
      quantity: 1,
      id: 294,
      Category: "oil",
      Name: "Dhara Refined Sunflower Oil ",
      Weight: 1,
      Unit: "Liter",
      MRP: 235,
      SP: 198,
    },
    {
      quantity: 1,
      id: 295,
      Category: "oil",
      Name: "Dhara Refined Sunflower Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3570,
      SP: 3019,
    },
    {
      quantity: 1,
      id: 296,
      Category: "Oil",
      Name: "Figaro Extra Virgin Olive Oil ",
      Weight: 500,
      Unit: "ml",
      MRP: 649,
      SP: 405,
    },
    {
      quantity: 1,
      id: 297,
      Category: "Oil",
      Name: "Figaro Olive Oil Tin ",
      Weight: 1,
      Unit: "liter",
      MRP: 999,
      SP: 765,
    },
    {
      quantity: 1,
      id: 298,
      Category: "oil",
      Name: "Fortune Filtered Groundnut Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 230,
      SP: 189,
    },
    {
      quantity: 1,
      id: 299,
      Category: "oil",
      Name: "Fortune Kachi Ghani Mustard Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 228,
      SP: 197,
    },
    {
      quantity: 1,
      id: 300,
      Category: "oil",
      Name: "Fortune Kachi Ghani Mustard Oil Bottle ",
      Weight: 1,
      Unit: "liter",
      MRP: 220,
      SP: 197,
    },
    {
      quantity: 1,
      id: 301,
      Category: "oil",
      Name: "Fortune Plus Soya Health Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 199,
      SP: 179,
    },
    {
      quantity: 1,
      id: 302,
      Category: "oil",
      Name: "Fortune Refined Sunflower Oil Tin ",
      Weight: 15,
      Unit: "liter",
      MRP: 3500,
      SP: 2949,
    },
    {
      quantity: 1,
      id: 303,
      Category: "oil",
      Name: "Fortune Rice Bran Health Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 225,
      SP: 186,
    },
    {
      quantity: 1,
      id: 304,
      Category: "oil",
      Name: "Fortune Rice Bran Health Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3400,
      SP: 2755,
    },
    {
      quantity: 1,
      id: 305,
      Category: "oil",
      Name: "Fortune Sunlite Refined Sunflower Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 230,
      SP: 205,
    },
    {
      quantity: 1,
      id: 306,
      Category: "oil",
      Name: "Fortune Sunlite Refined Sunflower Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3650,
      SP: 3039,
    },
    {
      quantity: 1,
      id: 307,
      Category: "oil",
      Name: "Fortune Vivo Blended Oil ",
      Weight: 5,
      Unit: "liter",
      MRP: 1150,
      SP: 919,
    },
    {
      quantity: 1,
      id: 308,
      Category: "oil",
      Name: "Gemini Refined Soyabean Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 215,
      SP: 185,
    },
    {
      quantity: 1,
      id: 309,
      Category: "oil",
      Name: "Gemini Refined Sunflower Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3550,
      SP: 3049,
    },
    {
      quantity: 1,
      id: 310,
      Category: "oil",
      Name: "Gemini Refined Sunflower Oil ",
      Weight: 5,
      Unit: "liter",
      MRP: 1225,
      SP: 1049,
    },
    {
      quantity: 1,
      id: 311,
      Category: "oil",
      Name: "Gemini Rice Bran Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 215,
      SP: 181,
    },
    {
      quantity: 1,
      id: 312,
      Category: "oil",
      Name: "Godrej Refined Sunflower Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3520,
      SP: 2999,
    },
    {
      quantity: 1,
      id: 313,
      Category: "oil",
      Name: "Godrej Vanaspati ",
      Weight: 1,
      Unit: "liter",
      MRP: 195,
      SP: 173,
    },
    {
      quantity: 1,
      id: 314,
      Category: "oil",
      Name: "Gramiyaa Wood Cold Pressed Coconut Oil ",
      Weight: 500,
      Unit: "ml",
      MRP: 235,
      SP: 180,
    },
    {
      quantity: 1,
      id: 315,
      Category: "oil",
      Name: "Gramiyaa Wood Cold Pressed Groundnut Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 380,
      SP: 290,
    },
    {
      quantity: 1,
      id: 316,
      Category: "oil",
      Name: "Gramiyaa Wood Cold Pressed Sesame Oil ",
      Weight: 500,
      Unit: "ml",
      MRP: 295,
      SP: 210,
    },
    {
      quantity: 1,
      id: 317,
      Category: "oil",
      Name: "Guinea Filtered Groundnut Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3500,
      SP: 2669,
    },
    {
      quantity: 1,
      id: 318,
      Category: "oil",
      Name: "Guinea Filtered Groundnut Oil ",
      Weight: 5,
      Unit: "liter",
      MRP: 1275,
      SP: 1099,
    },
    {
      quantity: 1,
      id: 319,
      Category: "oil",
      Name: "Guinea Lite Groundnut Oil ",
      Weight: 5,
      Unit: "liter",
      MRP: 1275,
      SP: 1099,
    },
    {
      quantity: 1,
      id: 320,
      Category: "oil",
      Name: "Gulab Filtered Groundnut Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 235,
      SP: 183,
    },
    {
      quantity: 1,
      id: 321,
      Category: "oil",
      Name: "Gulab Filtered Groundnut Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3459,
      SP: 2685,
    },
    {
      quantity: 1,
      id: 322,
      Category: "oil",
      Name: "Gulab Sunflower Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 238,
      SP: 187,
    },
    {
      quantity: 1,
      id: 323,
      Category: "oil",
      Name: "Gulab Sunflower Oil Jar ",
      Weight: 15,
      Unit: "liter",
      MRP: 3589,
      SP: 2825,
    },
    {
      quantity: 1,
      id: 324,
      Category: "oil",
      Name: "Hudson Canola Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 299,
      SP: 199,
    },
    {
      quantity: 1,
      id: 325,
      Category: "oil",
      Name: "Idhayam Gingelly Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 334,
      SP: 295,
    },
    {
      quantity: 1,
      id: 326,
      Category: "oil",
      Name: "Idhayam Sesame Oil Bottle ",
      Weight: 1,
      Unit: "liter",
      MRP: 351,
      SP: 305,
    },
    {
      quantity: 1,
      id: 327,
      Category: "oil",
      Name: "KLF Coconad 100% Pure Coconut Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 330,
      SP: 220,
    },
    {
      quantity: 1,
      id: 328,
      Category: "Oil",
      Name: "KPL Shudhi Coconut Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 268,
      SP: 228,
    },
    {
      quantity: 1,
      id: 329,
      Category: "Oil",
      Name: "Leonardo Extra Light Olive Oil ",
      Weight: 2,
      Unit: "liter",
      MRP: 2599,
      SP: 1400,
    },
    {
      quantity: 1,
      id: 330,
      Category: "oil",
      Name: "Leonardo Olive Pomace Oil ",
      Weight: 5,
      Unit: "liter",
      MRP: 4099,
      SP: 1899,
    },
    {
      quantity: 1,
      id: 331,
      Category: "Oil",
      Name: "Nature Fresh Refined Sunflower Oil Pouch ",
      Weight: 1,
      Unit: "liter",
      MRP: 240,
      SP: 199,
    },
    {
      quantity: 1,
      id: 332,
      Category: "oil",
      Name: "Patanjali Kachi Ghani Mustard Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 195,
      SP: 184,
    },
    {
      quantity: 1,
      id: 333,
      Category: "Oil",
      Name: "Patanjali Kachi Ghani Mustard Oil Pouch ",
      Weight: 1,
      Unit: "liter",
      MRP: 200,
      SP: 189,
    },
    {
      quantity: 1,
      id: 334,
      Category: "Oil",
      Name: "RRO Mastdil Premium Mustard Oil Bottle ",
      Weight: 1,
      Unit: "liter",
      MRP: 265,
      SP: 211,
    },
    {
      quantity: 1,
      id: 335,
      Category: "Oil",
      Name: "RRO Til Dil Premium Til Oil Bottle ",
      Weight: 1,
      Unit: "liter",
      MRP: 360,
      SP: 286,
    },
    {
      quantity: 1,
      id: 336,
      Category: "oil",
      Name: "Saffola Active Oil ",
      Weight: 1,
      Unit: "liter",
      MRP: 225,
      SP: 189,
    },
    {
      quantity: 1,
      id: 337,
      Category: "oil",
      Name: "Saffola Active Oil ",
      Weight: 15,
      Unit: "liter",
      MRP: 3400,
      SP: 3130,
    },
    {
      quantity: 1,
      id: 338,
      Category: "Oil",
      Name: "Sunny Sun Lite Refined Sunflower Oil Jar ",
      Weight: 15,
      Unit: "Liut",
      MRP: 3915,
      SP: 2949,
    },
    {
      quantity: 1,
      id: 339,
      Category: "Oil",
      Name: "Sweekar Refined Sunflower Oil Jar ",
      Weight: 15,
      Unit: "Li t",
      MRP: 3600,
      SP: 3109,
    },
    {
      quantity: 1,
      id: 340,
      Category: "Oil",
      Name: "Tez Mustard Kachchi Ghani Oil Bottle ",
      Weight: 1,
      Unit: "liter",
      MRP: 235,
      SP: 202,
    },
    {
      quantity: 1,
      id: 341,
      Category: "Oil",
      Name: "Tez Mustard Kachchi Ghani Oil Pouch ",
      Weight: 1,
      Unit: "liter",
      MRP: 231,
      SP: 199,
    },
    {
      quantity: 1,
      id: 342,
      Category: "Oil",
      Name: "Tilsona Til Oil Bottle ",
      Weight: 1,
      Unit: "liter",
      MRP: 365,
      SP: 315,
    },
  ],
  Ghee: [
    {
      quantity: 1,
      id: 343,
      Category: "ghee",
      Name: "Gowardhan Pure Cow Ghee ",
      Weight: 1,
      Unit: "liter",
      MRP: 629,
      SP: 550,
    },
    {
      quantity: 1,
      id: 344,
      Category: "ghee",
      Name: "Mother Dairy Pure Cow Ghee ",
      Weight: 1,
      Unit: "Litr",
      MRP: 550,
      SP: 475,
    },
    {
      quantity: 1,
      id: 345,
      Category: "ghee",
      Name: "Organic India Organic Cow Ghee ",
      Weight: 500,
      Unit: "ml",
      MRP: 650,
      SP: 585,
    },
  ],
  Breakfast: [
    {
      quantity: 1,
      id: 346,
      Category: "breakfast",
      Name: "Dabur Hommade Coconut Milk ",
      Weight: 200,
      Unit: "ml",
      MRP: 75,
      SP: 69,
    },
    {
      quantity: 1,
      id: 347,
      Category: "breakfast",
      Name: "Lapsi Rava Small Daliya ",
      Weight: 500,
      Unit: "gm",
      MRP: 30,
      SP: 24,
    },
    {
      quantity: 1,
      id: 348,
      Category: "breakfast",
      Name: "Miki Maize (Makai) Poha ",
      Weight: 500,
      Unit: "gm",
      MRP: 42,
      SP: 33,
    },
    {
      quantity: 1,
      id: 349,
      Category: "breakfast",
      Name: "Mix Chana Vatana (for Sprout) ",
      Weight: 500,
      Unit: "gm",
      MRP: 74,
      SP: 67,
    },
    {
      quantity: 1,
      id: 350,
      Category: "breakfast",
      Name: "Organic Tattva Red Poha ",
      Weight: 500,
      Unit: "gm",
      MRP: 80,
      SP: 53,
    },
    {
      quantity: 1,
      id: 351,
      Category: "breakfast",
      Name: "Premia Amchur Powder ",
      Weight: 100,
      Unit: "gm",
      MRP: 40,
      SP: 32,
    },
    {
      quantity: 1,
      id: 352,
      Category: "breakfast",
      Name: "Premia Red Poha ",
      Weight: 500,
      Unit: "gm",
      MRP: 34,
      SP: 29,
    },
    {
      quantity: 1,
      id: 353,
      Category: "breakfast",
      Name: "Premia Refined Rice Bran Oil ",
      Weight: 1,
      Unit: "Litr",
      MRP: 190,
      SP: 159,
    },
    {
      quantity: 1,
      id: 354,
      Category: "breakfast",
      Name: "Rajma Red Small ",
      Weight: 500,
      Unit: "gm",
      MRP: 1,
      SP: 53,
    },
    {
      quantity: 1,
      id: 355,
      Category: "breakfast",
      Name: "Red Rice ",
      Weight: 1,
      Unit: "kg",
      MRP: 62,
      SP: 51,
    },
    {
      quantity: 1,
      id: 356,
      Category: "breakfast",
      Name: "Ricela Refined Rice Bran Oil ",
      Weight: 5,
      Unit: "Litr",
      MRP: 1115,
      SP: 915,
    },
    {
      quantity: 1,
      id: 357,
      Category: "breakfast",
      Name: "Royal Delight Finest Mabroom Dates ",
      Weight: 250,
      Unit: "gm",
      MRP: 425,
      SP: 282,
    },
    {
      quantity: 1,
      id: 358,
      Category: "breakfast",
      Name: "Satyam Khobra (Coconut) ",
      Weight: 200,
      Unit: "gm",
      MRP: 108,
      SP: 99,
    },
    {
      quantity: 1,
      id: 359,
      Category: "breakfast",
      Name: "Snapin Cheesy Garlic Bread Mix ",
      Weight: 45,
      Unit: "gm",
      MRP: 99,
      SP: 79,
    },
    {
      quantity: 1,
      id: 360,
      Category: "breakfast",
      Name: "24 Mantra Organic Red Poha ",
      Weight: 500,
      Unit: "gm",
      MRP: 75,
      SP: 37,
    },
  ],
};

export default products;
